### ISSUE TITLE
[ERROR] Trying to retrieve setting with no value given: 'max_feedrate_z_override'

### ISSUE THREAD

**Issue by joeljoseph17** [KrisRoofe/curaengine-dockerfile#2]
I'm running into the following error? Can you help me? 

Thanks,
Joel

**Comment by joeljoseph17** [comment]
[ERROR] Trying to retrieve setting with no value given: 'max_feedrate_z_override'

**Comment by fozbek** [comment]
I have no time to fix that for now. You can use that temporarily.
`./CuraEngine slice -p -j ./fdmprinter.def.json -j prusa_i3.def.json -s max_feedrate_z_override="0" -s material_flow="100" -l herringbone-gear-large.stl -o herringbone-gear-large.gcode`

**Comment by fozbek** [comment]
@joeljoseph17 i have fixed the problem, can checkout master and try again?

**Comment by campoy** [comment]
I just tried and it's still failing with the same error.

That said, thanks for this repo! Super useful! ❤️

**Comment by campoy** [comment]
And even running the program with those extra parameters I get a new error:

```
[ERROR] Trying to retrieve setting with no value given: 'skin_alternate_rotation'
```

**Comment by fozbek** [comment]
@campoy The pull request is still open. Can u try my fork?
https://github.com/fozbek/curaengine-dockerfile
